"""empty message

Revision ID: 83695825a22d
Revises: e68206696fe3
Create Date: 2021-10-05 17:31:02.233739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83695825a22d'
down_revision = 'e68206696fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Gallery', 'thumnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Gallery', sa.Column('thumnail', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
